name: emp_mapper
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - seqkit
  - gzip
  - parallel
  - nanofilt
  - minibar
  - vsearch
  - minimap2
  - samtools
